FROM openjdk:21-jdk-slim
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN apt-get update && apt-get install -y maven
RUN mvn dependency:go-offline -B
RUN mvn package -DskipTests
ENTRYPOINT ["java", "-jar", "target/sistema-atendimento-0.0.1-SNAPSHOT.jar"]