spring.application.name=Sistema de atendimento
# application.properties

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/atendimento_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
